### PR TITLE
Desktop view redesigned #9

### PR DESCRIPTION
**Pull request by DugarRishab**
This Pull request resolves issue #9 
-  3 column grid is created
-  the above was done using flex. 
-  The screenshot below shows the updated desktop design

Screenshot 2022-10-01 001038

### CODE REVIEW

**Comment by Swastikyadav** [comment]
Awesome!

Looks good to me for now. Merging it.

**Comment by DugarRishab** [comment]
@Swastikyadav can you please add the tag `hacktober-accepted` to make it count?

**Comment by Swastikyadav** [comment]
Done!

**Comment by Swastikyadav** [comment]
@DugarRishab It will be really nice of you, if you can give this repository a star. You will find the star button on top right of this page.

**Pull request merged**
